spring:
  application:
    name: zerowaste

  datasource:
    url: jdbc:postgresql://localhost:5432/zerowaste
    username: postgres
    password: abhkayani

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true